// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpLV0kOo5fv-On5GI-8W1lFtj-ImXn8p0',
    appId: '1:1044561080940:web:b45d1abf8a5068da881e49',
    messagingSenderId: '1044561080940',
    projectId: 'failure-mode-effect-analysis',
    authDomain: 'failure-mode-effect-analysis.firebaseapp.com',
    databaseURL: 'https://failure-mode-effect-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'failure-mode-effect-analysis.appspot.com',
    measurementId: 'G-244P0567GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMLoYDoYpMIXjZqBqZA3Aj-Hc_cYm7rvE',
    appId: '1:1044561080940:android:c98fad3123b8168a881e49',
    messagingSenderId: '1044561080940',
    projectId: 'failure-mode-effect-analysis',
    databaseURL: 'https://failure-mode-effect-analysis-default-rtdb.firebaseio.com',
    storageBucket: 'failure-mode-effect-analysis.appspot.com',
  );
}
